title: Alex Fennell # your name (or website title) here
logo: "/images/Meresize.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Soon to be PhD graduate in Cognitive Psychology from The Ohio State University with over a decade of data wrangling experience. My research has revolved around applying a stochastic model of decision making, the diffusion decision model, to understand how visual working memory is represented in mind and how this representation influences the decision making process. 

  I have a passion for learning and improving myself especially when it comes to understanding data. I am always trying to learn more about about statistical, computational, and machine learning methods in order to examine a dataset from as many perspectives as possible. Through coursework I have learned many statistical techniques such as multivariate linear regression, logistic regression, and Bayesian analysis and what questions these techniques can answer. I have applied these methodologies to class projects in addition to some of my publications. 
  <br><br>
  <a href="https://www.linkedin.com/in/alex-fennell/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
