title: Alex Fennell # your name (or website title) here
logo: "/images/Meresize.png?raw=true" # your photo (or logo) here
description: > 
  Welcome to my portfolio! I am PhD graduate student in Cognitive Psychology from The Ohio State University with over a decade of data wrangling experience.
  I am looking to use my statistical and experimental skills to delve into data science. Here are some recent projects I have completed for fun. 
  If you have any questions or just want to chat, feel free to reach to me on LinkedIn!

  <br><br>
  <a href="https://www.linkedin.com/in/alex-fennell/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
github:
  is_project_page: false
